version: "3.1"

services:
  notebook:
    command: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/home/jovyan/spatialpy"
      - "./tmp:/tmp"
    ports:
      - "8888:8888"
      - "5000:5000"
