Import('env')
libspatialpy_core = env.Object([
    'count_cores.c',
    'model.c',
    'NRMConstant_v5.cpp',
    'output.c',
    'particle.cpp',
    'pthread_barrier.c',
    'read_lammps_input_file.c',
    'simulate.cpp',
    'simulate_rdme.cpp',
    'simulate_threads.c'
])
Return('libspatialpy_core')
