# This is a basic unit test workflow for SpatialPy

name: SpatialPy Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker-compose build

      - name: Run unit tests
        run: docker-compose run notebook coverage run spatialpy/test/run_tests.py 
