name: Publish SpatialPy Docs

on:
  push:
    branches: [develop-clone]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      uses: actions/checkout@v2
      with:
        ref: develop
      
    - name: Update and Publish docs
      working-directory: docs
      run: |
        ls ../.github/workflows/
        make publish-release
