name: Publish SpatialPy Docs

on:
  push:
    branches: [testing_auto_deploy_docs]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      uses: actions/checkout@v2
      with:
        ref: testing_auto_deploy_docs
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install Sphinx Dependency
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -U sphinx
        python3 -m pip install numpy
        python3 -m pip install -r requirements.txt

    - name: Update and Publish docs
      working-directory: docs
      with:
        repo-token: ${{secrets.GITHUB_TOKEN }}
      #env:
      #  # user: __token__
      #  # password: ${{ secrets.GITHUB_TOKEN }}
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make publish-release
