name: Publish SpatialPy Docs

on:
  push:
    branches: [develop-clone]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      uses: actions/checkout@v2
      with:
        ref: develop-clone
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install Sphinx Dependency
      run: python3 pip install -U sphinx

    - name: Update and Publish docs
      working-directory: docs
      run: |
        ls ../.github/workflows/
        make publish-release
