name: Publish SpatialPy Docs

on:
  push:
    branches: [develop-clone]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      uses: actions/checkout@develop-clone
      # uses: StochSS/SpatialPy@develop-clone
      
    - name: Update and Publish docs
      working-directory: docs
      run: make publish-release
