name: Publish SpatialPy Docs

on:
  push:
    branches: [develop-clone]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Update and Publish docs
      # working-directory: /docs
      run: pwd
